### ISSUE TITLE
Refresh the project

### ISSUE THREAD

**Issue by rakhimov** [yuzhichang/cppdep#3]
Thanks for rewriting the tools from C.
I believe this is a great tool and want to use it, but it is not working with newer networkx.
The project seems to be in an inactive state with the issues still open.
I have been working on getting it fixed on my [fork](https://github.com/rakhimov/cppdep)
and refresh the project.
Some critical goals (I think):
- [ ] Refactor the code for modern Python 2 & 3 (PEP 8 conformance)
- [ ] Move to newer versions of networkx
- [ ] Write tests
- [ ] Provide pypi package

I wouldn't like to continue with my fork by myself.
It would be great if @yuzhichang and other folks are still interested in getting this package to work.

**Comment by yuzhichang** [comment]
Thanks for your interest of this tool. 
This repo is inactive since I was not working on C++ projects recently.
I just made the latest master to use the latest networkx and PyGraphviz.

The networkx API changes from version to version. 
Python dependency management is a headache. I think Pypi is good for libraries but not for tools such as this repo. Maybe the better way to manage dependency is packing all into a Docker image.

**Comment by rakhimov** [comment]
Hi @yuzhichang , nice to hear from you that the project isn't dead.
I went ahead with the todo list on my [repo](https://github.com/rakhimov/cppdep).
There's still a lot to do, but at least it is working. (Didn't Lakos think of tests?! Well, probably he didn't know about unit testing at the time;-)

I wouldn't agree that pypi isn't good for tools and complicate things with a Docker image. The problem is that networkx doesn't seem to be terribly familiar with 'semantic versioning'.

My current commits are pretty messy for PRs because I didn't think of separating them into topical branches. It would be more like joining a fork into the codebase (think of a blob :-).
Please take a look at my repo, and we need to synchronize the services (CI, test, QA, pypi).
It would make the merge a lot less messier.

**Comment by rakhimov** [comment]
Closing in favor of the [fork](https://github.com/rakhimov/cppdep)
